name: pre-commit-check

on:
    pull_request:
    push:
    workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo pip install pre-commit
    - run: echo "pre_commit=`pre-commit run --color never --from-ref HEAD^ --to-ref HEAD 2>&1`" >> $GITHUB_ENV

    - name: PR number
      if: github.event_name == 'pull_request'
      run: |
        export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        echo "pr_num=$PR_NUMBER" >> $GITHUB_ENV

    - name: Add Comment
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request' && env.pre_commit_status == 'ERROR'
      with:
        script: |
            await github.rest.issue.createComment({
                issue_number: ${{ env.pr_num }},
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `${{ env.pre_commit }}`
            }) 

