name: pre-commit-check

on:
    pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo pip install pre-commit
    - run: pre-commit install
    - run: |
        echo "pre_commit<<EOF" >> $GITHUB_ENV
        echo "`pre-commit run --color never --all-files 2>&1`" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Prepare comment
      env:
        PRE_COMMIT: ${{ env.pre_commit }}
      run: |
        echo "$PRE_COMMIT"
        br='<br/>'
        results=`echo "$PRE_COMMIT" |  while read line; do echo $line$br; done | tr -d '\n'`
        echo "pre_commit_mod=$results" >> $GITHUB_ENV
    - name: Add comment to PR
      env:
        URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PRE_COMMIT: ${{ env.pre_commit_mod }}
      run: |
        curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data "{ \"body\": \"$PRE_COMMIT\" }"