name: pre-commit-check

on:
    pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo pip install pre-commit
    - run: |
        echo "pre_commit<<EOF" >> $GITHUB_ENV
        echo "`pre-commit run --color never --from-ref HEAD^ --to-ref HEAD 2>&1`" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: PR number
      if: github.event_name == 'pull_request'
      run: |
        export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        echo "pr_num=$PR_NUMBER" >> $GITHUB_ENV

    - name: Add comment to PR
      env:
        URL: ${{ github.event.pull_request.comments_url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "blah blah" }'

