name: SIT

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  sit-regression:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - run: echo Hello, world!
    - run: docker run hello-world
